"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-xspch$pq+zw#ngrs+-v-)dj%u48nuj9-np$=qxdeqru0(x2*7%'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get('DJANGO_DEBUG', '0')).strip().lower() in {'1', 'true', 'yes', 'on'}

_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').strip()
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(',') if host.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

_csrf_trusted_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _csrf_trusted_origins.split(',') if origin.strip()]

USE_X_FORWARDED_HOST = str(os.environ.get('DJANGO_USE_X_FORWARDED_HOST', '1')).strip().lower() in {
    '1', 'true', 'yes', 'on'
}
if str(os.environ.get('DJANGO_SECURE_PROXY_SSL_HEADER', '0')).strip().lower() in {'1', 'true', 'yes', 'on'}:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

_force_script_name = os.environ.get('DJANGO_FORCE_SCRIPT_NAME', '').strip()
if _force_script_name:
    if not _force_script_name.startswith('/'):
        _force_script_name = '/' + _force_script_name
    FORCE_SCRIPT_NAME = _force_script_name.rstrip('/') or '/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'base.middleware.SimSearchDebugHeadersMiddleware',
]

ROOT_URLCONF = 'djangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

try:
    _db_timeout = max(1.0, float(os.environ.get('DJANGO_DB_TIMEOUT', '30') or '30'))
except (TypeError, ValueError):
    _db_timeout = 30.0

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH', str(BASE_DIR / 'db.sqlite3')),
        'OPTIONS': {
            'timeout': _db_timeout,
        },
    }
}
try:
    CONN_MAX_AGE = max(0, int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '60') or '60'))
except (TypeError, ValueError):
    CONN_MAX_AGE = 60

SESSION_ENGINE = os.environ.get(
    'DJANGO_SESSION_ENGINE',
    'django.contrib.sessions.backends.file'
).strip() or 'django.contrib.sessions.backends.file'
if SESSION_ENGINE == 'django.contrib.sessions.backends.file':
    SESSION_FILE_PATH = os.environ.get(
        'DJANGO_SESSION_FILE_PATH',
        str(BASE_DIR / 'runtime' / 'sessions')
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

if _force_script_name:
    STATIC_URL = f"{FORCE_SCRIPT_NAME}/static/"
    MEDIA_URL = f"{FORCE_SCRIPT_NAME}/media/"
else:
    STATIC_URL = 'static/'
    MEDIA_URL = '/media/'

# Media files (user uploaded content and external images)
MEDIA_ROOT = BASE_DIR / 'media'

# External image directory configuration.
# Defaults to server dataset path, falls back to local project folder.
DEFAULT_SERVER_IMAGE_BASE_PATH = '/share/datasets/profimedia/data-images'
IMAGE_BASE_PATH = os.environ.get(
    'SIMSEARCH_IMAGE_BASE_PATH',
    DEFAULT_SERVER_IMAGE_BASE_PATH if os.path.isdir(DEFAULT_SERVER_IMAGE_BASE_PATH) else str(BASE_DIR / 'data-images')
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
