# Generated by Django 5.2.7 on 2025-12-07 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetricMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_data', models.BinaryField()),
                ('matrix_dimension', models.IntegerField(default=768)),
                ('scaling_factor', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_learning_model', models.CharField(default='OMDML', max_length=50)),
                ('model_hyperparameters', models.JSONField(default=dict)),
                ('feedback_type', models.IntegerField(default=1)),
                ('feedback_hyperparameters', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric_matrix', to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=20)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('query_image_index', models.IntegerField(blank=True, null=True)),
                ('query_vector', models.BinaryField(blank=True, null=True)),
                ('result_image_index', models.IntegerField()),
                ('result_image_name', models.CharField(max_length=500)),
                ('feedback_type', models.CharField(choices=[('positive', 'Relevant'), ('negative', 'Irrelevant')], max_length=10)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='base.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'session_id'], name='base_feedba_user_id_119f0f_idx')],
            },
        ),
    ]
