# Generated by Django 5.2.7 on 2026-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetricmatrix',
            name='distance_mode',
            field=models.CharField(choices=[('euclidean', 'Euclidean'), ('dot_product', 'Dot Product')], default='euclidean', help_text='Distance mode for filter-and-refine search', max_length=20),
        ),
    ]
