# Generated by Django 5.2.7 on 2026-02-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usermetricmatrix_distance_mode'),
    ]

    operations = []
