# Generated by Django 5.2.7 on 2026-03-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appliedfeedbacksession'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS base_appliedfeedbacksession;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
