# Generated by Codex on 2026-05-31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_appliedfeedbacksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackApplyJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_apply_jobs', to='base.user')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'session_id', 'status'], name='base_feedba_user_id_e3473d_idx'),
                    models.Index(fields=['created_at'], name='base_feedba_created_ebaacc_idx'),
                ],
            },
        ),
    ]
