# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_feedbackapplyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetricmatrix',
            name='feedback_type',
            field=models.IntegerField(default=2),
        ),
    ]
